<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'name' => 'SMKN 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL. PANGERAN SOGIRI NO. 404 TANAH BARU BOGOR',
                'maps' => 'https://www.google.com/maps?q=Jl.+Menteng+Raya+No.+1,+Jakarta',
                'contact' => '6287777227210',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMKS BINA WARGA 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL PANGERAN SOGIRI NO. 404 TANAH BARU BOGOR UTARA',
                'maps' => 'https://www.google.com/maps?q=Jl.+Menteng+Raya+No.+1,+Jakarta',
                'contact' => '6285692189748',
                'status' => 'pending',
                'pic' => 'Pak Wawan',
            ],
            [
                'name' => 'SMAS REGINA PACIS',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'PABATON',
                'address' => 'JL. IR HJ. JUANDA NO. 2',
                'maps' => 'https://share.google/JuvJMRfIw4EaLuLqt',
                'contact' => '81119260001',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMKS WIKRAMA BOGOR',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'SIDANGSARI',
                'address' => 'JL. RAYA WANGUN KEL. SINDANGSARI',
                'maps' => 'https://share.google/dbvMdK3HxItm08L8e',
                'contact' => '628112232880',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'PKBM TUNAS MEKAR',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'SIDANGSARI',
                'address' => 'Kp. Wangun tengah RT 2/2',
                'maps' => 'https://share.google/i9UqbXqt8J78oNUeR',
                'contact' => '6287876109155',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMK-SMAK BOGOR',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'BARANANGSIANG',
                'address' => 'JALAN BINAMARGA I, CIHEULEUT BARANANGSIANG',
                'maps' => 'https://share.google/mgoktullcwGmLEAdm',
                'contact' => '6285156323250',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMAS PGRI 1',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'BARANANGSIANG',
                'address' => 'JL. BINA MARGA 1/17',
                'maps' => 'https://share.google/TAkXYxXci5C6Knuzk',
                'contact' => '6281361889990',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SEKOLAH MENENGAH ATAS BOGOR RAYA',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'TANAHBARU',
                'address' => 'Perumahan Danau Bogor Raya, Kota Bogor_Tanah sereal',
                'maps' => 'https://share.google/L7xObaSzlq24OWzLR',
                'contact' => '6281398902600',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'PKBM INSAN MANDIRI',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'TAJUR',
                'address' => 'Jl. Raya Tajur Gg. Balai Desa No. 10',
                'maps' => 'https://share.google/G9rIRArE9CxpAVCJZ',
                'contact' => '6282218419548',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMKS BINA PUTERA BOGOR',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'KATULAMPA',
                'address' => 'Jl Pengairan Katulampa',
                'maps' => 'https://share.google/5CqG1K0UN3YlmZuv1',
                'contact' => '6289652397178',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMK BINA BUDI LUHUR BOGOR',
                'kota' => 'KOTA BOGOR ',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'KATULAMPA',
                'address' => 'JL.KATULAMPA RT004 RW009',
                'maps' => 'https://share.google/kQ2CkmIDxbcY790AM',
                'contact' => '-',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMKS PEMBANGUNAN',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Bantarjati',
                'address' => 'JL PAJAJARAN NO. 63',
                'maps' => 'https://share.google/T6EHDi57gXlnILMU7',
                'contact' => '6281387187883',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMAS YPHB',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Bantarjati',
                'address' => 'JL.PAJAJARAN NO.234',
                'maps' => 'https://share.google/A4iBMkqx3J3mseUdG',
                'contact' => '6285714988063',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMAN 8 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Bantarjati',
                'address' => 'JL. BTN CIPARIGI NO. 60',
                'maps' => 'https://share.google/A4iBMkqx3J3mseUdG',
                'contact' => '6285714988063',
                'status' => 'pending',
                'pic' => '-',
            ],
            [
                'name' => 'SMKS KARYA NUGRAHA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Ciparigi',
                'address' => ' JL. MANDALA BLK. NO. 16 CIPARIGI BOGOR.',
                'maps' => 'https://share.google/eEoNwQOtM3oXwboTa',
                'contact' => ' - ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMAN 7 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => ' JL. PALUPUH NO. 7',
                'maps' => 'https://share.google/Fg7B04TATtx4n3e3P',
                'contact' => ' - ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMAN 7 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => ' JL. PALUPUH NO. 7',
                'maps' => 'https://share.google/Fg7B04TATtx4n3e3P',
                'contact' => ' - ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMKS KAMANDAKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => ' Jl. Ahmad Sobana, SH ',
                'maps' => ' https://share.google/ueMN0O9oDsJMqBOW9 ',
                'contact' => ' 6281385509941 ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMKS ANALISIS KIMIA YKPI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => '  JL. H. ACHMAD SOBANA, SH (BANGBARUNG) PERUMNAS BANTARJATI BOGOR',
                'maps' => ' https://share.google/lEO7JjtaHzYqueTL8 ',
                'contact' => ' 6287874742626',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMAS KAMANDAKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => '  Jl. Achmad Sobana, SH ',
                'maps' => ' https://maps.app.goo.gl/qptkNB134kqihB546 ',
                'contact' => ' - ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMAS KAMANDAKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => '  Jl. Achmad Sobana, SH ',
                'maps' => ' https://maps.app.goo.gl/qptkNB134kqihB546 ',
                'contact' => ' - ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMKS TRI DHARMA 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kebon Pedes',
                'address' => '   JL RAYA KEBON PEDES NO. 25 BOGOR ',
                'maps' => ' https://maps.app.goo.gl/bGBSbBBjVrTZEfR49 ',
                'contact' => ' 628211002827 ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMKS TRI DHARMA 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kebon Pedes',
                'address' => '   JL. KEBON PEDES NO. 46 BOGOR ',
                'maps' => ' https://maps.app.goo.gl/WASdoizP9vKkUXgY7 ',
                'contact' => ' 81218222424 ',
                'status' => 'pending',
                'pic' => '-',

            ],
            [
                'name' => 'SMKN 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Tanah Sereal',
                'address' => 'JL. HEULANG NO. 6 BOGOR',
                'maps' => 'https://maps.app.goo.gl/X7zyZXomb9DXrNDXA',
                'contact' => '6281573882798',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 6 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Tanah Sereal',
                'address' => 'JL. WALET NO 13',
                'maps' => 'https://maps.app.goo.gl/aQP8a5xddq4HkR1Q9',
                'contact' => '628125342700',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Sukaresmi',
                'address' => 'JL. KERANJI UJUNG NO. 1 BUDI AGUNG',
                'maps' => 'https://maps.app.goo.gl/RCxVX3foJSnWgjdY6',
                'contact' => '6285726119166',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'PKBM DAMAI MEKAR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Sukaresmi',
                'address' => 'Kp. Situpete RT 003/001',
                'maps' => 'https://maps.app.goo.gl/WMEQ7Zs45jo7fGD89',
                'contact' => '6282119057795',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMK YAK 1',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kencana',
                'address' => 'KALIMURNI',
                'maps' => 'https://maps.app.goo.gl/wdRkxqNzUhVD2E136',
                'contact' => '68771180596',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMK NU GLOBAL MADANI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Cilebut Barat',
                'address' => 'KP. BOJONG JENGKOL BARAT, RT 03/10 Sukaraja',
                'maps' => 'https://maps.app.goo.gl/MsZujj3DGruki6JaA',
                'contact' => '8179822140',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 5 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Menteng',
                'address' => 'JL. MANUNGGAL NO. 22',
                'maps' => 'https://maps.app.goo.gl/XcPmgiRAJwr1NGKh9',
                'contact' => '6282298647288',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'MAN 1 KOTA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Menteng',
                'address' => 'JL. DR. SEMERU KMP BUMI MENTENG ASRI, Menteng',
                'maps' => 'https://maps.app.goo.gl/jiDcq34np3DQSC3X6',
                'contact' => '628159322737',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMKS YZA 3 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Kebonkelapa',
                'address' => 'Jl. Raya Wangun RT. 005 RW. 001 Kel. Sindangsari',
                'maps' => 'https://maps.app.goo.gl/8GywgbrvVopiHkj56',
                'contact' => null,
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMKS YZA 4 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Kebonkelapa',
                'address' => 'JL. DR. SEMERU NO. 59 BOGOR',
                'maps' => 'https://maps.app.goo.gl/YZxR2oTBzpShqYcV8',
                'contact' => null,
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMKS TELEKOMEDIKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Bubulak',
                'address' => 'Jl. Cifor Kp. Bubulak RT. 02/RW. 07 Kel. Bubulak',
                'maps' => 'https://maps.app.goo.gl/NtqFKumZXaskCqDu5',
                'contact' => '6281388978894',
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMKS TUNAS BANGSA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Bubulak',
                'address' => 'JALAN RAYA CIFOR NO. 60 BATUHULUNG',
                'maps' => 'https://maps.app.goo.gl/E5QYTaEWdruYvBff9',
                'contact' => null,
                'status' => 'pending',
                'pic' => null,
            ],
            [
                'name' => 'SMKN 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL. PANGERAN SOGIRI NO. 404 TANAH BARU BOGOR',
                'maps' => 'https://maps.app.goo.gl/yRcn8HYCqqthELde6',
                'contact' => '6287777227210',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMK BINA WARGA 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL. PANGERAN SOGIRI NO. 404 TANAH BARU BOGOR UTARA',
                'maps' => 'https://maps.app.goo.gl/PQHGi2pExQhtc6i98',
                'contact' => '6285692189748',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS BINA WARGA 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL PANGERAN SOGIRI NO. 404 TANAH BARU CILUAR BOGOR',
                'maps' => 'https://maps.app.goo.gl/GPiqrPNWVYKVhfmi7',
                'contact' => '628161113489',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMK NUSANTARA KOTA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => '-',
                'address' => 'JL. BATARA NO. 13 RT 05 RW 02',
                'maps' => 'https://maps.app.goo.gl/1r86a4GBU8vvhoAw8',
                'contact' => '6281952512183',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAS IT UMMUL QURO',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kayumanis',
                'address' => 'JL. Pool Binamarga',
                'maps' => 'https://maps.app.goo.gl/py9Ao5DgZF7eBT4T6',
                'contact' => '6282315492471',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS BOGOR MUHIDIN SCHOOL BMS',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Mekarwangi',
                'address' => 'KH. AHMAD SYAYANI KP. MASJID No.54',
                'maps' => 'https://maps.app.goo.gl/FT6mbtgh3fgagzgB6',
                'contact' => '81513327597',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS INFOKOM BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Sindangbarang',
                'address' => 'JL. LETDJEN IBRAHIM ADJIE NO. 178 SINDANG BARANG',
                'maps' => 'https://maps.app.goo.gl/Y1cCsGiKR1bLgjr39',
                'contact' => '6282246336161',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS AL AZHAR PLUS KOTA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Sindangbarang',
                'address' => 'JL. RAYA SINDANG BARANG NO. 219 BOGOR',
                'maps' => 'https://maps.app.goo.gl/Txavc4JC41DfVGa26',
                'contact' => '6285283871845',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAN 10 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Curugmekar',
                'address' => 'Jl. Pinang Raya Komp. Yasmin Sektor VI',
                'maps' => 'https://maps.app.goo.gl/jRKBUNxkTq5C2cPC8',
                'contact' => '6281210477600',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMA BINA INSAN MANDIRI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Cilendek Barat',
                'address' => 'Jl. Ponpes Baron RT.003 RW.013',
                'maps' => 'https://maps.app.goo.gl/qqqXGGcb2oDxXovX7',
                'contact' => '6285668191369',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS YKTB 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Semplak',
                'address' => 'Jl. Raya Semplak KM. 3',
                'maps' => 'https://maps.app.goo.gl/hmBqpE6LpcUxoJT69',
                'contact' => '6287770319028',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAS RIMBA MADYA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Pasirmulya',
                'address' => 'JL. RIMBA MULYA II',
                'maps' => 'https://maps.app.goo.gl/sCYzqmJacuFBPGW17',
                'contact' => '6281316063447',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAS INSAN KAMIL',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Pasirjaya',
                'address' => 'JL. RD ARIA SURIALAGA BOGOR BARAT',
                'maps' => 'https://maps.app.goo.gl/bUy6opoBC8iG63bd6',
                'contact' => '6285838033459',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAS PESAT',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'loji',
                'address' => 'JL. PORAS NO.7',
                'maps' => 'https://maps.app.goo.gl/yEW28Tk4knVwYg4dA',
                'contact' => '6287789814768',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'PKBM HARAPAN JAYA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'loji',
                'address' => 'JL. SIAGA NO. 7',
                'maps' => 'https://maps.app.goo.gl/Py92UDDQSqAk64av7',
                'contact' => '6289660241000',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS INFORMATIKA PESAT',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'loji',
                'address' => 'JL. PORAS NO. 7 SINDANG BARANG LOJI KOTA BOGOR',
                'maps' => 'https://maps.app.goo.gl/q5qDDqoDi6k3iqkK7',
                'contact' => '6287711177442',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAN 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Paledang',
                'address' => 'JL. IR.H. JUANDA NO.16',
                'maps' => 'https://maps.app.goo.gl/B8Eg72bvrTvSsYLU7',
                'contact' => '6281578020303',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAS BUDI MULIA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Paledang',
                'address' => 'JL. KAPTEN MUSLIHAT',
                'maps' => 'https://maps.app.goo.gl/qarCSgs4jQJofUPV9',
                'contact' => '6285826612852',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMAS BUDI MULIA',
                'kota' => 'SMAN 3 BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'Baranangsiang',
                'address' => 'JL. PAKUAN 4',
                'maps' => 'https://maps.app.goo.gl/CwZ3jbyXrqX9te129',
                'contact' => '-',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'MAN 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'Baranangsiang',
                'address' => 'Jl. Raya Pajajaran No.6, Baranangsiang, Kec. Bogor Tim., Kota Bogor',
                'maps' => 'https://maps.app.goo.gl/6BiTzMoXfLsBeMXBA',
                'contact' => '6285694115988',
                'status' => 'pending',
                'pic' => '-',
            ],

            [
                'name' => 'SMKS BARANANGSIANG BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'Baranangsiang',
                'address' => 'JL RAYA PAJAJARAN NO. 6 BOGOR',
                'maps' => 'https://maps.app.goo.gl/MyhHoyZ9wYF6mYkUA',
                'contact' => '6282181529050',
                'status' => 'pending',
                'pic' => '-',
            ],

            // tambahkan lainnya...
        ];

        // Upsert berdasarkan kolom 'name' agar aman diulang
        School::upsert($rows, ['name']);
    }
}
