<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [

            [
                'name' => 'SMAS REGINA PACIS',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'PABATON',
                'address' => 'JL. IR HJ. JUANDA NO. 2',
                'maps' => 'https://maps.app.goo.gl/JuvJMRfIw4EaLuLqt',
                'contact' => '81119260001',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS WIKRAMA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'SIDANGSARI',
                'address' => 'JL. RAYA WANGUN KEL. SINDANGSARI',
                'maps' => 'https://maps.app.goo.gl/dbvMdK3HxItm08L8e',
                'contact' => '628112232880',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM TUNAS MEKAR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'SIDANGSARI',
                'address' => 'Kp. Wangun tengah RT 2/2',
                'maps' => 'https://maps.app.goo.gl/i9UqbXqt8J78oNUeR',
                'contact' => '6287876109155',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK-SMAK BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'BARANANGSIANG',
                'address' => 'JALAN BINAMARGA I, CIHEULEUT BARANANGSIANG',
                'maps' => 'https://maps.app.goo.gl/mgoktullcwGmLEAdm',
                'contact' => '6285156323250',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS PGRI 1',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'BARANANGSIANG',
                'address' => 'JL. BINA MARGA 1/17',
                'maps' => 'https://maps.app.goo.gl/TAkXYxXci5C6Knuzk',
                'contact' => '6281361889990',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SEKOLAH MENENGAH ATAS BOGOR RAYA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'TANAH BARU',
                'address' => 'Perumahan Danau Bogor Raya, RT.01/RW.07, Tanah Baru, Kec. Bogor Utara, Kota Bogor, Jawa Barat 16143',
                'maps' => 'https://maps.app.goo.gl/L7xObaSzlq24OWzLR',
                'contact' => '6281398902600',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM INSAN MANDIRI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'TAJUR',
                'address' => 'Jl. Raya Tajur Gg. Balai Desa No. 10',
                'maps' => 'https://maps.app.goo.gl/G9rIRArE9CxpAVCJZ',
                'contact' => '6282218419548',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS BINA PUTERA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'KATULAMPA',
                'address' => 'Jl Pengairan Katulampa',
                'maps' => 'https://maps.app.goo.gl/5CqG1K0UN3YlmZuv1',
                'contact' => '6289652397178',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK BINA BUDI LUHUR BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'KATULAMPA',
                'address' => 'JL.KATULAMPA RT004 RW009',
                'maps' => 'https://maps.app.goo.gl/kQ2CkmIDxbcY790AM',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PEMBANGUNAN',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Bantarjati',
                'address' => 'JL PAJAJARAN NO. 63',
                'maps' => 'https://maps.app.goo.gl/T6EHDi57gXlnILMU7',
                'contact' => '6281387187883',
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMAS YPHB',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Bantarjati',
                'address' => 'JL.PAJAJARAN NO.234',
                'maps' => 'https://maps.app.goo.gl/A4iBMkqx3J3mseUdG',
                'contact' => '6285714988063',
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMAN 8 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Bantarjati',
                'address' => 'JL. BTN CIPARIGI NO. 60',
                'maps' => 'https://maps.app.goo.gl/A4iBMkqx3J3mseUdG',
                'contact' => '6285714988063',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS KARYA NUGRAHA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Ciparigi',
                'address' => ' JL. MANDALA BLK. NO. 16 CIPARIGI BOGOR.',
                'maps' => 'https://maps.app.goo.gl/eEoNwQOtM3oXwboTa',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMAN 7 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => ' JL. PALUPUH NO. 7',
                'maps' => 'https://maps.app.goo.gl/Fg7B04TATtx4n3e3P',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMKS KAMANDAKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => ' Jl. Ahmad Sobana, SH ',
                'maps' => ' https://maps.app.goo.gl/ueMN0O9oDsJMqBOW9 ',
                'contact' => ' 6281385509941 ',
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMKS ANALISIS KIMIA YKPI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => '  JL. H. ACHMAD SOBANA, SH (BANGBARUNG) PERUMNAS BANTARJATI BOGOR',
                'maps' => ' https://maps.app.goo.gl/lEO7JjtaHzYqueTL8 ',
                'contact' => ' 6287874742626',
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMAS KAMANDAKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tegal Gundil',
                'address' => '  Jl. Achmad Sobana, SH ',
                'maps' => ' https://maps.app.goo.gl/qptkNB134kqihB546 ',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMKS TRI DHARMA 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kebon Pedes',
                'address' => '   JL RAYA KEBON PEDES NO. 25 BOGOR ',
                'maps' => ' https://maps.app.goo.gl/bGBSbBBjVrTZEfR49 ',
                'contact' => ' 628211002827 ',
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMKS TRI DHARMA 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kebon Pedes',
                'address' => '   JL. KEBON PEDES NO. 46 BOGOR ',
                'maps' => ' https://maps.app.goo.gl/WASdoizP9vKkUXgY7 ',
                'contact' => ' 81218222424 ',
                'status' => 'baru',
                'pic' => null,

            ],
            [
                'name' => 'SMKN 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Tanah Sereal',
                'address' => 'JL. HEULANG NO. 6 BOGOR',
                'maps' => 'https://maps.app.goo.gl/X7zyZXomb9DXrNDXA',
                'contact' => '6281573882798',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 6 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Tanah Sereal',
                'address' => 'JL. WALET NO 13',
                'maps' => 'https://maps.app.goo.gl/aQP8a5xddq4HkR1Q9',
                'contact' => '628125342700',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Sukaresmi',
                'address' => 'JL. KERANJI UJUNG NO. 1 BUDI AGUNG',
                'maps' => 'https://maps.app.goo.gl/RCxVX3foJSnWgjdY6',
                'contact' => '6285726119166',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM DAMAI MEKAR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Sukaresmi',
                'address' => 'Kp. Situpete RT 003/001',
                'maps' => 'https://maps.app.goo.gl/WMEQ7Zs45jo7fGD89',
                'contact' => '6282119057795',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK YAK 1',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kencana',
                'address' => 'KALIMURNI',
                'maps' => 'https://maps.app.goo.gl/wdRkxqNzUhVD2E136',
                'contact' => '68771180596',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK NU GLOBAL MADANI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kencana',
                'address' => 'Jl. Bojong Jengkol, RT.05/RW.01, Kencana, Kec. Tanah Sereal, Kota Bogor, Jawa Barat 16167',
                'maps' => 'https://maps.app.goo.gl/MsZujj3DGruki6JaA',
                'contact' => '8179822140',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 5 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Menteng',
                'address' => 'JL. MANUNGGAL NO. 22',
                'maps' => 'https://maps.app.goo.gl/XcPmgiRAJwr1NGKh9',
                'contact' => '6282298647288',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'MAN 1 KOTA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Menteng',
                'address' => 'JL. DR. SEMERU KMP BUMI MENTENG ASRI, Menteng',
                'maps' => 'https://maps.app.goo.gl/jiDcq34np3DQSC3X6',
                'contact' => '628159322737',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS YZA 3 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Menteng',
                'address' => 'Jl. DR. Sumeru No.59, RT.05/RW.08, Menteng',
                'maps' => 'https://maps.app.goo.gl/ZNcMHFcCsMAsgGNs6',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS YZA 4 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Kebonkelapa',
                'address' => 'JL. DR. SEMERU NO. 59 BOGOR',
                'maps' => 'https://maps.app.goo.gl/YZxR2oTBzpShqYcV8',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS TELEKOMEDIKA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Bubulak',
                'address' => 'Jl. Cifor Kp. Bubulak RT. 02/RW. 07 Kel. Bubulak',
                'maps' => 'https://maps.app.goo.gl/NtqFKumZXaskCqDu5',
                'contact' => '6281388978894',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS TUNAS BANGSA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Bubulak',
                'address' => 'JALAN RAYA CIFOR NO. 60 BATUHULUNG',
                'maps' => 'https://maps.app.goo.gl/E5QYTaEWdruYvBff9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK BINA WARGA 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL. PANGERAN SOGIRI NO. 404 TANAH BARU BOGOR UTARA',
                'maps' => 'https://maps.app.goo.gl/PQHGi2pExQhtc6i98',
                'contact' => '6285692189748',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS BINA WARGA 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => 'Tanah Baru',
                'address' => 'JL PANGERAN SOGIRI NO. 404 TANAH BARU CILUAR BOGOR',
                'maps' => 'https://maps.app.goo.gl/GPiqrPNWVYKVhfmi7',
                'contact' => '628161113489',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK NUSANTARA KOTA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR UTARA',
                'kelurahan' => null,
                'address' => 'JL. BATARA NO. 13 RT 05 RW 02',
                'maps' => 'https://maps.app.goo.gl/1r86a4GBU8vvhoAw8',
                'contact' => '6281952512183',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS IT UMMUL QURO',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Kayumanis',
                'address' => 'JL. Pool Binamarga',
                'maps' => 'https://maps.app.goo.gl/py9Ao5DgZF7eBT4T6',
                'contact' => '6282315492471',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS BOGOR MUHIDIN SCHOOL BMS',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'TANAH SEREAL',
                'kelurahan' => 'Mekarwangi',
                'address' => 'KH. AHMAD SYAYANI KP. MASJID No.54',
                'maps' => 'https://maps.app.goo.gl/FT6mbtgh3fgagzgB6',
                'contact' => '81513327597',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS INFOKOM BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Sindangbarang',
                'address' => 'JL. LETDJEN IBRAHIM ADJIE NO. 178 SINDANG BARANG',
                'maps' => 'https://maps.app.goo.gl/Y1cCsGiKR1bLgjr39',
                'contact' => '6282246336161',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS AL AZHAR PLUS KOTA BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Sindangbarang',
                'address' => 'JL. RAYA SINDANG BARANG NO. 219 BOGOR',
                'maps' => 'https://maps.app.goo.gl/Txavc4JC41DfVGa26',
                'contact' => '6285283871845',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAN 10 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Curugmekar',
                'address' => 'Jl. Pinang Raya Komp. Yasmin Sektor VI',
                'maps' => 'https://maps.app.goo.gl/jRKBUNxkTq5C2cPC8',
                'contact' => '6281210477600',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMA BINA INSAN MANDIRI',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Cilendek Barat',
                'address' => 'Jl. Ponpes Baron RT.003 RW.013',
                'maps' => 'https://maps.app.goo.gl/qqqXGGcb2oDxXovX7',
                'contact' => '6285668191369',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS YKTB 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Semplak',
                'address' => 'Jl. Raya Semplak KM. 3',
                'maps' => 'https://maps.app.goo.gl/hmBqpE6LpcUxoJT69',
                'contact' => '6287770319028',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS RIMBA MADYA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Pasirmulya',
                'address' => 'JL. RIMBA MULYA II',
                'maps' => 'https://maps.app.goo.gl/sCYzqmJacuFBPGW17',
                'contact' => '6281316063447',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS INSAN KAMIL',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Pasirjaya',
                'address' => 'JL. RD ARIA SURIALAGA BOGOR BARAT',
                'maps' => 'https://maps.app.goo.gl/bUy6opoBC8iG63bd6',
                'contact' => '6285838033459',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS PESAT',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'loji',
                'address' => 'JL. PORAS NO.7',
                'maps' => 'https://maps.app.goo.gl/yEW28Tk4knVwYg4dA',
                'contact' => '6287789814768',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'PKBM HARAPAN JAYA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'loji',
                'address' => 'JL. SIAGA NO. 7',
                'maps' => 'https://maps.app.goo.gl/Py92UDDQSqAk64av7',
                'contact' => '6289660241000',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS INFORMATIKA PESAT',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'loji',
                'address' => 'JL. PORAS NO. 7 SINDANG BARANG LOJI KOTA BOGOR',
                'maps' => 'https://maps.app.goo.gl/q5qDDqoDi6k3iqkK7',
                'contact' => '6287711177442',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAN 1 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Paledang',
                'address' => 'JL. IR.H. JUANDA NO.16',
                'maps' => 'https://maps.app.goo.gl/B8Eg72bvrTvSsYLU7',
                'contact' => '6281578020303',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS BUDI MULIA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TENGAH',
                'kelurahan' => 'Paledang',
                'address' => 'JL. KAPTEN MUSLIHAT',
                'maps' => 'https://maps.app.goo.gl/qarCSgs4jQJofUPV9',
                'contact' => '6285826612852',
                'status' => 'baru',
                'pic' => null,
            ],


            [
                'name' => 'MAN 2 BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'BARANANGSIANG',
                'address' => 'Jl. Raya Pajajaran No.6, Baranangsiang, Kec. Bogor Tim., Kota Bogor',
                'maps' => 'https://maps.app.goo.gl/6BiTzMoXfLsBeMXBA',
                'contact' => '6285694115988',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS BARANANGSIANG BOGOR',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR TIMUR',
                'kelurahan' => 'Baranangsiang',
                'address' => 'JL RAYA PAJAJARAN NO. 6 BOGOR',
                'maps' => 'https://maps.app.goo.gl/MyhHoyZ9wYF6mYkUA',
                'contact' => '6282181529050',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PELITA CIAMPEA 1',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'BENTENG',
                'address' => 'JL. RAYA WARUNG BORONG CIAMPEA',
                'maps' => 'https://maps.app.goo.gl/nxcaGpLTjuZ1sEP76',
                'contact' => '81284622141',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS PELITA CIAMPEA 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'BENTENG',
                'address' => 'JL. RAYA WARUNG BORONG CIAMPEA',
                'maps' => 'https://maps.app.goo.gl/CvT3yYqMv6yHFFZa7',
                'contact' => '81284622141',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS KESEHATAN PELITA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'BOJONG RANGKAS',
                'address' => 'JL. RAYA WARUNG BORONG CIAMPEA',
                'maps' => 'https://maps.app.goo.gl/yhLJyLi4kmP2iYEr6',
                'contact' => '87770646028',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAN 1 PAMIJAHAN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'GUNUNG SARI',
                'address' => 'JL. Gunung Salak Endah km. 03',
                'maps' => 'https://maps.app.goo.gl/PwEr9V5BdhtHCv100',
                'contact' => '82299362993',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS PGRI PAMIJAHAN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'GUNUNG SARI',
                'address' => 'JLN. GUNUNG SALAK ENDAH DESA GUNUNG SARI',
                'maps' => 'https://maps.app.goo.gl/TMuqU2S6ZfVdHtrb7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK KESEHATAN RAFLESIA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'GUNUNG SARI',
                'address' => 'Jl.Raya Gunung Salak Endah Kp.Pasar Jumat',
                'maps' => 'https://maps.app.goo.gl/QbhUPWw0yMTmSDFsX',
                'contact' => '88214791047',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS MUHAMMADIYAH PAMIJAHAN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIASMARA',
                'address' => 'Jln. K.H. Abdul Hamid Km.15, Kp. Sindang Baru',
                'maps' => 'https://maps.app.goo.gl/2JvaWzoUt2z4JZ9z6',
                'contact' => '85810957977',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS BUMI PUTERA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIASMARA',
                'address' => 'JL. KH. ABDUL HAMID KM. 15',
                'maps' => 'https://maps.app.goo.gl/e48M1caAfzbvW8c7h',
                'contact' => '85717805825',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK CIPTA MANDIRI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIASIHAN',
                'address' => 'JL. HM PARTA KM 03 KP SUKAMULYA RT03/05',
                'maps' => 'https://maps.app.goo.gl/59aknRkxzSPLUY288',
                'contact' => '85719013734',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS IBNU HAJAR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'PASAREAN',
                'address' => 'JL. KH. ABDUL HAMID KM .07 PASAREAN',
                'maps' => 'https://maps.app.goo.gl/rP8m4xbLywP49TL38',
                'contact' => '811194694',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS NURFADILLAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'PAMIJAHAN',
                'address' => 'KP.CILENGKONG RT 02/ RW 05',
                'maps' => 'https://maps.app.goo.gl/UuSc6ns2Z1Jrs8Gn8',
                'contact' => '85693079573',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS CENDIKIA MUSLIM',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'NANGGUNG',
                'kelurahan' => 'PARAKAN MUNCANG',
                'address' => 'JL RAYA ACE TABRANI KP LUKUT PARAKAN MUNCANG',
                'maps' => 'https://maps.app.goo.gl/FVAizr4FT6QBw72JD',
                'contact' => '85779453482',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMA 1 NANGGUNG',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'NANGGUNG',
                'kelurahan' => 'NANGGUNG',
                'address' => 'Jl. Pasir Sari Desa Nanggung',
                'maps' => 'https://maps.app.goo.gl/ns02sEjupo3PB3Hr6',
                'contact' => '81219866702',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'UNGGULAN CENDIKIA MUSLIM',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'NANGGUNG',
                'kelurahan' => 'PARAKAN MUNCANG',
                'address' => 'Jl. Raya Ace Tabrani Parakan Muncang',
                'maps' => 'https://maps.app.goo.gl/J89ywZ2U991NKU665',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'PKBM IMAM NAWAWI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'PAGELARAN',
                'address' => 'Jl. Raya CIOMAS Cikoneng Gg. Masjid No. 35 RT 001 RW 003',
                'maps' => 'https://maps.app.goo.gl/w7H2sB64nN2uJRai7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => "SMKS MA'ARIF NU CIOMAS",
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'PAGELARAN',
                'address' => 'JL. RAYA KRETEG NO 55 CIOMAS',
                'maps' => 'https://maps.app.goo.gl/zStW6kWXxZm4F5XR6',
                'contact' => '89634617338',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS MA ARIF NU',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'PAGELARAN',
                'address' => 'JL. RAYA KRETEG NO. 55 KP. SUKAJAYA RT. 01/02',
                'maps' => 'https://maps.app.goo.gl/dDEuG2A0eZZ0CYWKI',
                'contact' => '89834617338',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAN 1 CIOMAS',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'SUKAHARJA',
                'address' => 'JL. CIBINONG',
                'maps' => 'https://maps.app.goo.gl/38W9vcnospmd3ASDS',
                'contact' => '82220333622',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'PKBM LSM NOORWANGSANEGARA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'SUKAHARJA',
                'address' => 'Jl. Raya CIOMAS Babakan No.07',
                'maps' => 'https://maps.app.goo.gl/pe4UotNNNHGLPj947',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK BHAKTI MEDIKA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'PAGELARAN',
                'address' => 'JL. RAYA CIOMAS PERMAI NO 09',
                'maps' => 'https://maps.app.goo.gl/oKw5oqrE1JcZRK8J7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS IBNU AQIL BOGOR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'LALADON',
                'address' => 'JL.LALADON NO. 256 CIOMAS BOGOR',
                'maps' => 'https://maps.app.goo.gl/QqEhD2mVDBaw543P8',
                'contact' => '85817624288',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS IBNU AQIL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'LALADON',
                'address' => 'JL.LALADON NO. 256 CIOMAS BOGOR',
                'maps' => 'https://maps.app.goo.gl/QqEhD2mVDBaw543P8',
                'contact' => '85817624077',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS INFORMATIKA BINA GENERASI BOGOR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'PADASUKA',
                'address' => 'JL.CIKERTI NO.12',
                'maps' => 'https://maps.app.goo.gl/mdb3FushRZV3mLaa6',
                'contact' => '81348883386',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKN 1 LEUWILIANG',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'LEUWIMEKAR',
                'address' => 'Jl. Pabangbon',
                'maps' => 'https://maps.app.goo.gl/jUF1gj5t5lBCi1oHH',
                'contact' => '85770877752',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS BINA CENDIKA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'BARENGKOK',
                'address' => 'JL RAYA LEUWILIANG',
                'maps' => 'https://maps.app.goo.gl/13P5hGAgwqZ5wEiDx',
                'contact' => '82228691486',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'MAS UMMUL QURO AL ISLAMI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'LEUWIMEKAR',
                'address' => 'Jl. Moh Noh Nur Kp. Banyusuci Rt. 004 Rw. 004 Leuwimekar',
                'maps' => 'https://maps.app.goo.gl/vC7IYGI1q3dd0aafb',
                'contact' => '85219668112',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'MAS MU ALLIMIEN MUHAMMADIYAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'LEUWILIANG',
                'address' => 'Jl. Raya Leuwiliang No.106 Rt 01/12 Kp.pamagersari Leuwiliang',
                'maps' => 'https://maps.app.goo.gl/Tpmn9FhXifJQwyobN',
                'contact' => '8588211129',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'MAS AL GHIFFARI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'CIBEBER I',
                'address' => 'Kp. Warnasari Timur No.15 RT.01/12 Cibeber I',
                'maps' => null,
                'contact' => '6282122286259',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'MAS SUNANUL HUDA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => null,
                'kelurahan' => null,
                'address' => 'Kp. Sawah Rt. 02/02',
                'maps' => null,
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS GEO INFORMATIKA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'CIHIDEUNG ILIR',
                'address' => 'JL. CIHIDEUNG ILIR RT.06 RW.02 CIAMPEA',
                'maps' => 'https://maps.app.goo.gl/6cTZYVY6nuY5aeJc3',
                'contact' => '85706263032',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS FARMASI GALENIUM',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'CIHIDEUNG ILIR',
                'address' => 'JL RAYA CIBANTENG',
                'maps' => 'https://maps.app.goo.gl/jCHFZ3TwlhJvH0WaS',
                'contact' => '89606198471',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS AGRI INSANI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'CIHIDEUNG ILIR',
                'address' => 'JL. CIBANTENG PROYEK, DS CIHIDEUNG ILIR RT 04 RW 03',
                'maps' => 'https://maps.app.goo.gl/7GjZyFOTnJ88sLST6',
                'contact' => '81381340942',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS MADANI',
                'kota' => null,
                'kecamatan' => null,
                'kelurahan' => null,
                'address' => 'JL ABDUL FATAH KM 4 BABAKAN NYAMPLUNG',
                'maps' => null,
                'contact' => '85888302393',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS MADANI 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'CINANGKA',
                'address' => 'JL. ABDUL FATAH KM 4 BABAKAN NYAMPLUNG',
                'maps' => 'https://maps.app.goo.gl/d0U6kppCpN1pGhqrD',
                'contact' => '85888302393',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'PKBM YAPURA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'BOJONG JENGKOL',
                'address' => 'JL. ABDUL FATAH KP. KONDANG RT. 004 RW. 003',
                'maps' => 'https://maps.app.goo.gl/lCTYrxjKu0SDrigGB',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'PKBM SATYA WACANA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'SADENG',
                'address' => 'Jl. Raya Sadeng RT.02/01',
                'maps' => 'https://maps.app.goo.gl/63n3FHJc8LIhZVEGe',
                'contact' => '81213734061',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK YASALAM EL UMMAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'LEUWISADENG',
                'address' => 'Jl. Bayur Legok Manggu RT01/08 LEUWISADENG Bogor',
                'maps' => 'https://maps.app.goo.gl/BzOhik6roHnU27LTb',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'PKBM AL-ANWARIYAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'KALONG I',
                'address' => 'Kp. Mekar Jaya RT 01/0',
                'maps' => 'https://maps.app.goo.gl/tyW8JghbSzAGoxOSh',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS TERPADU ATAM BINA INSANI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'KALONG I',
                'address' => 'JL. ACE TABRANI KM. 01 PANJAUNGAN',
                'maps' => 'https://maps.app.goo.gl/Qg5TtzxdchXrqnBsU',
                'contact' => '85797307663',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK TERPADU ANTAM BINA INSANI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'KALONG I',
                'address' => 'ACE TABRANI KM 1 PANJAUNGAN',
                'maps' => 'https://maps.app.goo.gl/Ub7JTyPFEmTwEh317',
                'contact' => '8158950166',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMKS AL AMIN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIBENING',
                'address' => 'JL. TAMRIN NO. 1 CIBENING PAMIJAHAN BOGOR',
                'maps' => 'https://maps.app.goo.gl/vIwTrFkoE03rr6crF',
                'contact' => '85770774426',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMA AL AMIN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIBENING',
                'address' => 'Jl.TAMRIN No. 1 CIBENING',
                'maps' => 'https://maps.app.goo.gl/4q6BQwm4HRPJEKdJy',
                'contact' => '85882524905',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'MAS AL AMIN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'PAMIJAHAN',
                'address' => 'Jl.tamrin No.1 Ds.cibening Pamijahan Bogor',
                'maps' => null,
                'contact' => '85888380088',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK 2 AL AMIN SURYADINATA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'GUNUNG MENYAN',
                'address' => 'JL. RAYA GUNUNG SALAK ENDAH CIKONENG',
                'maps' => 'https://maps.app.goo.gl/w7BQX0K4j29edV6oE',
                'contact' => '81284243793',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS PLUS IBNU SINA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIBENING',
                'address' => 'JL. CIKAMPAK - SEGOG KM 9',
                'maps' => 'https://maps.app.goo.gl/cy8owtMA4QDjV51aZ',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMK TEKNOMEDIKA 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'CEMPLANG',
                'address' => 'Kp. Cemplang RT. 025 RW. 006 Desa Cemplang',
                'maps' => 'https://maps.app.goo.gl/Disev1YqokSyfcsq7',
                'contact' => '85218351235',
                'status' => 'baru',
                'pic' => null,
            ],

            [
                'name' => 'SMAS ISLAM PAMBUDI LUHUR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'PAMIJAHAN',
                'kelurahan' => 'CIBENING',
                'address' => 'JL. GUNUNG SALAK ENDAH DESA CIBENING PAMIJAHAN',
                'maps' => '',
                'contact' => '81211123050',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS AL HAFIDZ',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'Karyasari',
                'address' => 'Jl. Raya Karehkel-Leuwiliang Km.03, Pabuaran',
                'maps' => 'https://maps.app.goo.gl/ERT9R7esiDqMKiMv5',
                'contact' => '6281315057839',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS INOVATIF',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'Karyasari',
                'address' => 'JL HEGARASA NO 1 KM. 07',
                'maps' => 'https://maps.app.goo.gl/7ccDLkWkPoSvQf8G8',
                'contact' => '81291008847',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS MUHAMMADIYAH PURASEDA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'Puraseda',
                'address' => 'JL. RAYA PURASEDA LEUWILIANG',
                'maps' => 'https://maps.app.goo.gl/NpAiVr4izpkYEg7cA',
                'contact' => '81511540603',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK IT HIDAYATUL FALAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'Karyasari',
                'address' => 'JL. MOH NOH NOER KM 11 KP GUNUNG PARIUK RT 01 RW 10',
                'maps' => 'https://maps.app.goo.gl/mxxUzSmDUnATQtCD7',
                'contact' => '8561354004',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMA RAUDHATUL MUTTAQIN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWILIANG',
                'kelurahan' => 'Purasari',
                'address' => 'Kp. Sinarjaya RT.02 RW.01',
                'maps' => 'https://maps.app.goo.gl/KrJSJ2Jqmuz5PqKt8',
                'contact' => '81914663283',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 CIBUNGBULANG',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Cibatok',
                'address' => 'Jalan Kapten Dasuki Bakri Desa Cibatok 01',
                'maps' => 'https://maps.app.goo.gl/EaTuAMe1HQo6Spdz6',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS BUMI SEJAHTERA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Cibatok',
                'address' => 'Jl. Kapten Dasuki Bakri KM.1 Cibatok 1',
                'maps' => 'https://maps.app.goo.gl/7P6ns7ZJ737spADcA',
                'contact' => '881024143121',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM PELITA NUSANTARA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Cemplang',
                'address' => 'Jl. Cemplang Rt.09/11 Desa.Cemplang Kec.CIBUNGBULANG',
                'maps' => null,
                'contact' => '89514256247',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS BUMI SEJAHTERA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Cimanggu 1',
                'address' => 'JL. RAYA CIBUNGBULANG KM 18 DS. CIMANGGU I',
                'maps' => null,
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS TAMAN ISLAM',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Situ Udik',
                'address' => 'JL. KH. ABDUL HAMID KM. 4 SITU UDIK CIBUNGBULANG',
                'maps' => 'https://maps.app.goo.gl/6srKbDUGWXRRk87o7',
                'contact' => '6281399894125',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS ADZKIA KHARISMA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Situ Udik',
                'address' => 'JL. K.H ABDUL HAMID KM. 04 CEMPLANG',
                'maps' => 'https://maps.app.goo.gl/UGZrYxVyT2TkDv7E8',
                'contact' => '85719183393',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 CIAMPEA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Cibadak',
                'address' => 'JL. K.H ABDUL HAMID KM. 04 CEMPLANG',
                'maps' => 'https://maps.app.goo.gl/bmGT5MjkALo6JxjR6',
                'contact' => '62818893035',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK KOMPUTER INDONESIA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Bojong Rangkas',
                'address' => 'JL. RAYA CIBADAK KP KERTASARI RT01/03',
                'maps' => 'https://maps.app.goo.gl/Rcvh5K1fAi1r9LbJ9',
                'contact' => '89517379735',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS MIFTAAHUSH SHUDUUR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Cibuntu',
                'address' => 'JL GUNUNG SALAK ENDAH',
                'maps' => null,
                'contact' => '85694068016',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PANDU BOGOR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIBUNGBULANG',
                'kelurahan' => 'Girimulya',
                'address' => 'JL. RAYA CIBUNGBULANG KM.15 BOGOR',
                'maps' => 'https://maps.app.goo.gl/ZpWJa7wR3CiV641c8',
                'contact' => '81285897944',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PANDU 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Cibadak',
                'address' => 'Jl.RAYA CIAMPEA KM 15 RT 03 RW 08',
                'maps' => 'https://maps.app.goo.gl/CmPn88Q1eqfZm9v47',
                'contact' => '8111620149',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK MATUSHA DWI ELANG_CIBUNGBULANG',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Cibadak',
                'address' => 'Desa Girimulya RT 01 RW 01 CIBUNGBULANG Kab. Bogor',
                'maps' => 'https://maps.app.goo.gl/qpCyJGVG5ARn6Esc8',
                'contact' => '81380866853',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS TARBIYATUL FALAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Cinangka',
                'address' => 'JL. ABDUL FATAH KM 4 DESA CINANGKA',
                'maps' => 'https://maps.app.goo.gl/BoFZWXpX19nyiKVFA',
                'contact' => '85691553443',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS HANURA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIAMPEA',
                'kelurahan' => 'Cihideung Udik',
                'address' => 'JL. BABAKAN KEMANG DS. CIHIDEUNG UDIK',
                'maps' => 'https://maps.app.goo.gl/nYao9D3wwHfbrp4o8',
                'contact' => '81295027676',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM HAAZDIKIYAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'Sadeng',
                'address' => 'Kp. Paku RT.004/004',
                'maps' => 'https://maps.app.goo.gl/QijGL2i13afme3i66',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'MAS DARUL HIDAYAH (YANUHI)',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'Sadeng',
                'address' => 'Kp. Sadeng Kaum Rt.05/02 No.042 Sadeng',
                'maps' => 'https://maps.app.goo.gl/QijGL2i13afme3i66',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMA TAHFIDHIL QURAN AL-MUSTAQIMIYYAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'LEUWISADENG',
                'kelurahan' => 'Sadeng',
                'address' => 'Jl. Raya Sadeng RT. 001 RW. 002',
                'maps' => 'https://maps.app.goo.gl/yno18WJ2HnMTqyCs7',
                'contact' => '81617008793',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKN 1 CIOMAS',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CIOMAS',
                'kelurahan' => 'Laladon',
                'address' => 'JL. RAYA LALADON DS. LALADON KEC. CIOMAS',
                'maps' => 'https://maps.app.goo.gl/5d3uVrjoHeoeGp8d8',
                'contact' => '89618297321',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 TENJOLAYA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TENJOLAYA',
                'kelurahan' => 'Tapos',
                'address' => 'JL. RAYA LALADON DS. LALADON KEC. CIOMAS',
                'maps' => 'https://maps.app.goo.gl/Kf6pLDf58TEUAEmt8',
                'contact' => '85810441644',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS YAPURA 1',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TENJOLAYA',
                'kelurahan' => 'Situ Daun',
                'address' => 'JL. DESA SITUDAUN KAMPUNG CIKUPA',
                'maps' => 'https://maps.app.goo.gl/tocJ2KXsvZSc19ob8',
                'contact' => '6285811713473',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM PUJI RAHAYU',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TENJOLAYA',
                'kelurahan' => 'Situ Daun',
                'address' => 'Jl. Cikupa Rt. 003/001',
                'maps' => 'https://maps.app.goo.gl/A3qU8nZamwTSg8cw8',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK YAPURA 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TENJOLAYA',
                'kelurahan' => 'Situ Daun',
                'address' => 'Jl.CIKUPA SITU DAUN TENJOLAYA KAB. BOGOR',
                'maps' => 'https://maps.app.goo.gl/VH6Do4VY3RLBF5Go9',
                'contact' => '6285811713473',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM GRAHA WIDYA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TENJOLAYA',
                'kelurahan' => 'Situ Daun',
                'address' => 'Kp. Pasir Ipis',
                'maps' => 'https://maps.app.goo.gl/77xzoEXUw2kHuX5z6',
                'contact' => '6285718109022',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK GEMA BANGSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TENJOLAYA',
                'kelurahan' => 'Cibitung Tengah',
                'address' => 'Jl. ABDUL FATAH KM 7 RT 03 RW 01 TENJOLAYA BOGOR',
                'maps' => 'https://maps.app.goo.gl/8oXdMiJK9QxgUyFN8',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 DRAMAGA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'DRAMAGA',
                'kelurahan' => 'DRAMAGA',
                'address' => 'JL. RAYA DRAMAGA KM 07',
                'maps' => 'https://maps.app.goo.gl/4z3Po9TpCC3dUHk47',
                'contact' => '6285692720122',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK BINA SEJAHTERA 3',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Margajaya',
                'address' => 'JL. RADAR BARU NO. 8_Kota Bogor',
                'maps' => 'https://maps.app.goo.gl/FUtr8VxqtwaSD9y29',
                'contact' => '6281289381652',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK BINA SEJAHTERA 4',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Margajaya',
                'address' => 'JL. RADAR BARU NO. 8_Kota Bogor',
                'maps' => 'https://maps.app.goo.gl/PYcxsvYJmrhuyKb99',
                'contact' => '6281289381652',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS ADI SANGGORO',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'DRAMAGA',
                'kelurahan' => 'Babakan',
                'address' => 'Sengked No.1 Kampus IPB DRAMAGA Bogor',
                'maps' => 'https://maps.app.goo.gl/4brFnm6o41dbxBFi7',
                'contact' => '6281511727858',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS KORNITA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'DRAMAGA',
                'kelurahan' => 'Babakan',
                'address' => 'JL. TANJUNG KAMPUS IPB BOGOR, DESA BABAKAN',
                'maps' => 'https://maps.app.goo.gl/pSbDTs74LUVyDv3y8',
                'contact' => '6281511727858',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK YAFAHI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'DRAMAGA',
                'kelurahan' => 'Neglasari',
                'address' => 'KP. PERTEMUAN RT. 03/03 KEL. NEGLASARI',
                'maps' => 'https://maps.app.goo.gl/eYEdHHiXFqUjtPtu9',
                'contact' => '6285759650084',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS GLOBIN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'DRAMAGA',
                'kelurahan' => 'Sinar Sari',
                'address' => 'Jl. Cibeureum Tengah Rt. 06/01',
                'maps' => 'https://maps.app.goo.gl/ijNSUyiDn9Mob1FX8',
                'contact' => '6281216254545',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS BHAKTI INSAN PERSADA',
                'kota' => 'KOTA BOGOR',
                'kecamatan' => 'BOGOR BARAT',
                'kelurahan' => 'Margajaya',
                'address' => 'JL.PEMUDA DRAMAGA',
                'maps' => null,
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS BINA IKHWANI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'DRAMAGA',
                'kelurahan' => 'Sinar Sari',
                'address' => 'JL CIBEUREUM PETIR',
                'maps' => 'https://maps.app.goo.gl/GsNJ5526gBeQfUJ46',
                'contact' => '6287821610647',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM BAKTI NUSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'Sukamantri',
                'address' => 'Jl. Purbajaya No. 27 RT. 02/013',
                'maps' => 'https://maps.app.goo.gl/M6ddGUc4T1TAUCUQ7',
                'contact' => '628164848690',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK BAKTI NUSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'Sukamantri',
                'address' => 'JL. PURBAJAYA/WARU. NO.27. KP. KIARALAWANG',
                'maps' => 'https://maps.app.goo.gl/Vmyg7TiBtJSgyTyH8',
                'contact' => '628158832060',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 TAMANSARI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'TAMANSARI',
                'address' => 'JL. JAGA KARSA DESA TAMAN SARI',
                'maps' => 'https://maps.app.goo.gl/Qi1am1cqcSPorQjh9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMA ISLAM TERPADU NURUL FIKRI BOARDING SCHOOL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'Sukaluyu',
                'address' => 'Jl. Jami RT002/008 Ciapus Bogor',
                'maps' => 'https://maps.app.goo.gl/LhupXD3ichp4Nwt98',
                'contact' => '6285779798040',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK SATRIA BANGSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'Sukajadi',
                'address' => 'Jl.GADOG SISI',
                'maps' => 'https://maps.app.goo.gl/RJB824MtsMTVGjim9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS NURUL HIDAYAH 1 BOGOR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'TAMANSARI',
                'address' => 'Jl. Kapten Yusuf Kp. Sukamanah Rt.01 Rw. 02',
                'maps' => 'https://maps.app.goo.gl/sPFxdYG1RM6kt9Ed9',
                'contact' => '6282111127312',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS ISLAM HASMI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TAMANSARI',
                'kelurahan' => 'TAMANSARI',
                'address' => 'Jln. Raya Cimanglid, Ciapus',
                'maps' => 'https://maps.app.goo.gl/sPFxdYG1RM6kt9Ed9',
                'contact' => '6281389919692',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS INSAN MADANI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'SUKAJAYA',
                'kelurahan' => 'Urug',
                'address' => 'JL RAYA CIPATAT KM 13 SUKAJAYA',
                'maps' => 'https://maps.app.goo.gl/vNjFNwGTZmAoajhu9',
                'contact' => '6285773460437',
                'status' => 'baru',
                'pic' => null,
            ],

            /* CILEUNGSI */
            [
                'name' => 'SMKN 1 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Limus Nunggal',
                'address' => 'JL. RAYA NAROGONG - CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/DWKeVacrPAorzpcNA',
                'contact' => '82125437098',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS FAJAR SETOSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Limus Nunggal',
                'address' => 'JL.PERUM GRIYA ALAM SENTOSA KP.BAKOM RT.03/04',
                'maps' => 'https://maps.app.goo.gl/rn8cnLXPypfHWSfk8',
                'contact' => '85217035075',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'JL. PASAR LAMA NO. 66 CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/pBvejyrfAhp9VRsm6',
                'contact' => '8129494354',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS BINA TEKNIKA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Dayeuh',
                'address' => 'JALAN HA GHOFAR KP. DAYEUH RT 003 RW 001 CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/JqokM5PeKgrKmwAf7',
                'contact' => '81283541977',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS MUHAMMADIYAH 2 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Dayeuh',
                'address' => 'JL. AKSES DESA DAYEUH NO.97B. CILEUNGSI- BOGOR',
                'maps' => 'https://maps.app.goo.gl/D4SM1AhEag6pGdFZ9',
                'contact' => '89517057112',
                'status' => 'baru',
                'pic' => null,
            ],

            /* GUNUNG PUTRI */
            [
                'name' => 'SMKN 1 GUNUNG PUTRI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Wanaherang',
                'address' => 'Jl. Barokah No. 06 Desa Wanaherang Kec. GUNUNG PUTRI',
                'maps' => 'https://maps.app.goo.gl/m9443EkyBeXfWybf8',
                'contact' => '82170070106',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS GENERASI MANDIRI GUNUNG PUTRI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Wanaherang',
                'address' => 'Jl. Barokah No. 06 Desa Wanaherang Kec. GUNUNG PUTRI',
                'maps' => 'https://maps.app.goo.gl/PJgGj1Yrxftp8mzw8',
                'contact' => '81289424995',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 GUNUNG PUTRI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Bojong Nangka',
                'address' => 'Jl. Sanding 2, Rt 015 Rw 007 Bojong Nangka 16963',
                'maps' => 'https://maps.app.goo.gl/2ggYpfNYSvMm953C7',
                'contact' => '895320059750',
                'status' => 'baru',
                'pic' => null,
            ],
            // PKBM HIDAYATURRAHMAN (dedup: hanya 1 entri)
            [
                'name' => 'PKBM HIDAYATURRAHMAN',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Bojong Nangka',
                'address' => 'Jl. Bojong Nangka',
                'maps' => 'https://maps.app.goo.gl/9gbycyQrzKHaknEz9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 2 GUNUNG PUTRI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Ciangsana',
                'address' => 'Jl. Boulevard Utama Kota Wisata Cibubur',
                'maps' => 'https://maps.app.goo.gl/HKKR2wADgWgmCUc9A',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            // PKBM ALSAFARA (dedup: hanya 1 entri)
            [
                'name' => 'PKBM ALSAFARA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Ciangsana',
                'address' => 'Kp. Cikeas Ilir RT.02/03',
                'maps' => 'https://maps.app.goo.gl/vSBrU4UMVuGa9tUY6',
                'contact' => '81314655122',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM SMART BANGUN NEGERI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'GUNUNG PUTRI',
                'kelurahan' => 'Ciangsana',
                'address' => 'Kp. Pabuaran Kulon RT.001/041',
                'maps' => 'https://maps.app.goo.gl/H1cMPCGvDMCoa5Bk9',
                'contact' => '85891098504',
                'status' => 'baru',
                'pic' => null,
            ],

            /* JONGGOL */
            [
                'name' => 'SMAN 1 JONGGOL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukasirna',
                'address' => 'JL. SUKASIRNA JONGGOL NO. 36',
                'maps' => 'https://maps.app.goo.gl/3Ja24KS3gZLrdEQN9',
                'contact' => '81213149884',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMA AQL ISLAMIC SCHOOL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukasirna',
                'address' => 'Jl. Irigasi Kampung Rawei Blok Perum ASABRI',
                'maps' => 'https://maps.app.goo.gl/HXVqXtqkgu2Z6YxYA',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS NURUL HIKMAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukamanah',
                'address' => 'JL. RAYA JONGGOL CIBUCIL SUKAMANAH JONGGOL BOGOR',
                'maps' => 'https://maps.app.goo.gl/yzL3LtNpiiJktuE69',
                'contact' => '89601730930',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS NURUL HIKMAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukamanah',
                'address' => 'JL. RAYA JONGGOL KP. CIBUCIL RT. 008/003 DS. SUKAMANAH JONGGOL',
                'maps' => 'https://maps.app.goo.gl/KgTqU5vg4cA5niD17',
                'contact' => '89601730930',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'MAN 3 Bogor',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukamaju',
                'address' => 'Jl. Rawa Gumbira No.39 RT. 003/004, Sukamaju, Kec. JONGGOL, Kabupaten Bogor',
                'maps' => 'https://maps.app.goo.gl/Qi6HM1nvWUGDZT5u9',
                'contact' => '85778024208',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS BINA INSAN JONGGOL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukamaju',
                'address' => 'JL. BARU MENAN DESA SUKAMAJU KEC. JONGGOL',
                'maps' => 'https://maps.app.goo.gl/fuPrLEgxeuc6kqSh8',
                'contact' => '85711247153',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM ALIP AL MARWAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'Sukamaju',
                'address' => 'Kp.Cipondok RT 003 RW 05',
                'maps' => 'https://maps.app.goo.gl/D2qYzhr4gkNmgqjF9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 2 JONGGOL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'JONGGOL',
                'address' => 'Jl. Irigasi Kp. Bengkok RT 002/009',
                'maps' => 'https://maps.app.goo.gl/2rqmbxd9xaKqyKix7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PUTRA NEGARA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'JONGGOL',
                'kelurahan' => 'JONGGOL',
                'address' => 'JL. HAUR KUNING JONGGOL',
                'maps' => 'https://maps.app.goo.gl/xsuZYppCqRAZ67Fz7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            /* KLAPANUNGGAL */
            [
                'name' => 'SMAN 1 KLAPANUNGGAL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'KLAPANUNGGAL',
                'address' => 'JL. TERUSAN BOJONG',
                'maps' => 'https://maps.app.goo.gl/9TU4R7NDQpCp9y7z5',
                'contact' => '87720814029',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS AN NUR KLAPANUNGGAL',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'Cikahuripan',
                'address' => 'JL. KLAPANUNGGAL-CIPEUCANG',
                'maps' => 'https://maps.app.goo.gl/9TU4R7NDQpCp9y7z5',
                'contact' => '88294959440',
                'status' => 'baru',
                'pic' => null,
            ],
            // MAS DAARUL MUGHNI (dedup: hanya 1 entri)
            [
                'name' => 'MAS DAARUL MUGHNI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'KLAPANUNGGAL',
                'address' => 'Jl. KLAPANUNGGAL, Kp. Cibeber II, Ds. Cikahuripan',
                'maps' => 'https://maps.app.goo.gl/At2jrDetAWAbcD4n9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM TERPADU AL KAUTSAR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'Nambo',
                'address' => 'Kp. Lebak Pasar RT.04/02',
                'maps' => 'https://maps.app.goo.gl/3zmzCdacMQ4btQcf7',
                'contact' => '81311583421',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMA SMART CIBINONG',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'Kembang Kuning',
                'address' => 'Jl. Raya Narogong Km. 7',
                'maps' => 'https://maps.app.goo.gl/Lmn6R93cJvDLePv9A',
                'contact' => '82210777883',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS 2 AMAL MULIA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'Kembang Kuning',
                'address' => 'JL. AMAL MULIA NO. 12 KLAPANUNGGAL',
                'maps' => 'https://maps.app.goo.gl/TSWUC1yaND3MLH7T6',
                'contact' => '87885430504',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS 1 AMAL MULIA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'KLAPANUNGGAL',
                'kelurahan' => 'Kembang Kuning',
                'address' => 'JL. AMAL MULIA NO. 12 KLAPANUNGGAL BOGOR',
                'maps' => 'https://maps.app.goo.gl/x2zLC3Mi53GUUKAWA',
                'contact' => '81944117107',
                'status' => 'baru',
                'pic' => null,
            ],

            /* SUKAMAKMUR */
            [
                'name' => 'SMAN 1 SUKAMAKMUR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'SUKAMAKMUR',
                'kelurahan' => 'Sukamulya',
                'address' => 'Jln. Raya AMD Desa Sukamulya',
                'maps' => 'https://maps.app.goo.gl/xtBb8mWv4H6y8udB9',
                'contact' => '85715391227',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS PUSPA BANGSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'SUKAMAKMUR',
                'kelurahan' => 'Cibadak',
                'address' => 'JL. RAYA SURUPAN',
                'maps' => 'https://maps.app.goo.gl/FuXWdVnu8LNa9x5V9',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS ISLAM SOLALATUL HUDA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'SUKAMAKMUR',
                'kelurahan' => 'Sirnajaya',
                'address' => 'JL AMD TEGALLEGA',
                'maps' => 'https://maps.app.goo.gl/6cPgnFke2a8SDShc9',
                'contact' => '85282022878',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PGRI SUKAMAKMUR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'SUKAMAKMUR',
                'kelurahan' => 'Pabuaran',
                'address' => 'JL. RAYA CITEUREUP - SUKAMAKMUR',
                'maps' => 'https://maps.app.goo.gl/6cPgnFke2a8SDShc9',
                'contact' => '81517495717',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'PKBM DARUL ILMI WADDA WAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'SUKAMAKMUR',
                'kelurahan' => 'Pabuaran',
                'address' => 'Kp. Pabuaran RT.003/005',
                'maps' => 'https://maps.app.goo.gl/f8R6suV2egLARVMJ7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],

            /* CARIU */
            [
                'name' => 'SMKN 1 CARIU',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CARIU',
                'kelurahan' => 'Babakan Raden',
                'address' => 'JL. BABAKAN RADEN NO. 807 CARIU',
                'maps' => 'https://maps.app.goo.gl/pKMsmFCVmPcLBP879',
                'contact' => '85694655535',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK AN-NUR CARIU',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CARIU',
                'kelurahan' => 'Sukajadi',
                'address' => 'JL. CARIU - LOJI KM 05 KP. CIMERTA',
                'maps' => 'https://maps.app.goo.gl/pKMsmFCVmPcLBP879',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 1 CARIU',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CARIU',
                'kelurahan' => 'Cariu',
                'address' => 'JL. RAYA CARIU',
                'maps' => 'https://maps.app.goo.gl/nnYUMMk86f7wNWbE7',
                'contact' => '81294049909',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK MUHAMMADIYAH CARIU LABSCHOOL OF UHAMKA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CARIU',
                'kelurahan' => 'Cariu',
                'address' => 'Jl. Mekarwangi Siliwangi Pahae RT 015 RW 005',
                'maps' => 'https://maps.app.goo.gl/NEeAzdsn3gD4rXzK7',
                'contact' => '85779024958',
                'status' => 'baru',
                'pic' => null,
            ],

            /* TANJUNGSARI */
            [
                'name' => 'SMAN 1 TANJUNGSARI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TANJUNGSARI',
                'kelurahan' => 'Antajaya',
                'address' => 'SMAN 1 TANJUNGSARI',
                'maps' => 'https://maps.app.goo.gl/acvR3s8RgoaxG2B57',
                'contact' => '81292964553',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK TEKNOLOGI DAN BISNIS INDONESIA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TANJUNGSARI',
                'kelurahan' => 'Jaka Mulya',
                'address' => 'Tanjungrasa, TANJUNGSARI, Bogor Regency, West Java 16840',
                'maps' => 'https://maps.app.goo.gl/pDpq8zRB5g7GoszBA',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS MANBAUL HUDA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TANJUNGSARI',
                'kelurahan' => 'Sirnasari',
                'address' => 'Jl. Transyogi Serena, Ds. Sirnasari',
                'maps' => 'https://maps.app.goo.gl/NpVT9M1S28kHYYTH7',
                'contact' => '6281220001409',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK TUNAS SINAR MANDIRI 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => null,
                'kelurahan' => null,
                'address' => 'Jl. Transyogi, TANJUNGSARI, Kab. Bogor',
                'maps' => 'https://maps.app.goo.gl/NpVT9M1S28kHYYTH7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK TUNAS SINAR MANDIRI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'TANJUNGRASA',
                'kelurahan' => 'Tanjungrasa',
                'address' => 'Jl. Transyogi, Tanjungrasa, Kec. TANJUNGSARI',
                'maps' => 'https://maps.app.goo.gl/DyspWQcYMGQuoG8p6',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 2 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Cipenjo',
                'address' => 'Komplek Metland Transyogi, Jl. Gandaria Utara No. 2, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/f6fEiHkE6rHtbBmw6',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS YPB CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Limus Nunggal',
                'address' => 'Jl. Setu Rawa Hingkik RT 01/01',
                'maps' => 'https://maps.app.goo.gl/a2PPasb8DFGE4oc58',
                'contact' => '6281289457548',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS MUHAMMADIYAH CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Jl. Anggrek No. 25, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/aXUc5aWMWrsZSopj6',
                'contact' => '6281316870605',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK YAPA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Blok Pandai RT 01/17, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/ea47GrJJhx6f7nEA6',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => "PKBM AL-ISTI'ANAH",
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Blok Pandai, Kp. Rawa Hingkik RT 001/017',
                'maps' => 'https://maps.app.goo.gl/cmesMqSJvNH7ahhBA',
                'contact' => '6285772126834',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMA REGINA CAELI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI Kidul',
                'address' => 'Perum Metland Transyogi KM 1, CILEUNGSI, Bogor',
                'maps' => 'https://maps.app.goo.gl/kh1pRp99n4bXnrKt7',
                'contact' => '6285218326352',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS WIDYA KUSUMA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Jl. Thata Hijau Raya Boulevard, Perum. CILEUNGSI Hijau',
                'maps' => 'https://maps.app.goo.gl/Dyo8dDXYWWvraSou8',
                'contact' => '6287711219031',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS WIDYA KUSUMA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI Kidul',
                'address' => 'Jl. Raya Boulevard, Perum. CILEUNGSI Hijau',
                'maps' => 'https://maps.app.goo.gl/Dyo8dDXYWWvraSou8',
                'contact' => '6283819195473',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PIJAR ALAM 2',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Gandoang',
                'address' => 'Jl. Puri Panangga RT 01/RW 10, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/aQqkrh1tXhP1Q6eG7',
                'contact' => '6285885904797',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK GLOBAL SURYA PRATAMA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Mekarsari',
                'address' => 'Jl. Puri Panangga RT 01/RW 10, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/sTGS8P8JLu9Rs13Z7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS PGRI KARISMA BANGSA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Gandoang',
                'address' => 'Jl. CILEUNGSI-JONGGOL KM 6',
                'maps' => 'https://maps.app.goo.gl/FktdHNNEEyRXWXnA8',
                'contact' => '628569958107',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS AL FARABI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Mekarsari',
                'address' => 'Jl. CILEUNGSI-JONGGOL KM 3',
                'maps' => 'https://maps.app.goo.gl/W3LYmmkzZbqTRjHm6',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS MUHAMMADIYAH 1 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Jl. Anggrek 86/1, Perum PTSC, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/yYB9HeUt4JWoUoHc9',
                'contact' => '6281213067544',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS MUHAMMADIYAH 3 CILEUNGSI BOGOR',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Jl. Anggrek No. 86/1, Perumahan PT.SC, CILEUNGSI, Bogor',
                'maps' => 'https://maps.app.goo.gl/PeN2xHE5Ktfh9mYz8',
                'contact' => '6283834153888',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAS DAARUL ISTIQOMAH',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI',
                'address' => 'Jl. H. Satibi No. 25, CILEUNGSI',
                'maps' => 'https://maps.app.goo.gl/pnPEbccdJgQkMheK7',
                'contact' => null,
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS DARMA BAKTI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Cipeucang',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 09, Kp. Tengah RT 08/RW 04',
                'maps' => 'https://maps.app.goo.gl/8Cd2SGy5mUB6fBej9',
                'contact' => '6281293040821',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS FARMASI BHAKTI KENCANA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Cipeucang',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 09 RT 008/RW 004, Kp. Tengah',
                'maps' => 'https://maps.app.goo.gl/asH8hD4hN9rVcN236',
                'contact' => '6287860244980',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS FATAHILLAH CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Cipeucang',
                'address' => 'Kp. Tengah RT 06/RW 03',
                'maps' => 'https://maps.app.goo.gl/qJL2iGAXHRpXJhtz5',
                'contact' => '6281212754284',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS BPS&K 2 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Cipeucang',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 10',
                'maps' => 'https://maps.app.goo.gl/1uqDj7GjN8Too9QA9',
                'contact' => '628129809734',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS BPS&K 1 CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'Cipeucang',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 10',
                'maps' => 'https://maps.app.goo.gl/mXUz8UUaRkFGmm5G6',
                'contact' => '628129809734',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMK BINA MANDIRI MULTIMEDIA',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI Kidul',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 1 No. 12',
                'maps' => 'https://maps.app.goo.gl/GtfPsqYhNCrJUHSo6',
                'contact' => '6281311596411',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMKS AVICENNA CILEUNGSI',
                'kota' => 'KABUPATEN BOGOR',
                'kecamatan' => 'CILEUNGSI',
                'kelurahan' => 'CILEUNGSI Kidul',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 01, Kab. Bogor, Jawa Barat',
                'maps' => 'https://maps.app.goo.gl/ywoQc22xnV5dHE4L8',
                'contact' => '628131544609',
                'status' => 'baru',
                'pic' => null,
            ],
            [
                'name' => 'SMAN 372',
                'kota' => 'JAKARTA TIMUR',
                'kecamatan' => 'kebayoran baru',
                'kelurahan' => 'CILEUNGSI Kidul',
                'address' => 'Jl. Raya CILEUNGSI-JONGGOL KM 01, Kab. Bogor, Jawa Barat',
                'maps' => 'https://maps.app.goo.gl/ywoQc22xnV5dHE4L8',
                'contact' => '628131544609',
                'status' => 'baru',
                'pic' => null,
            ],


            // tambahkan lainnya...
        ];

        // Upsert berdasarkan kolom 'name' agar aman diulang
        School::upsert($rows, ['name']);
    }
}
